apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-56fv
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/bootstrap/integration1-jbgd-tenant/integ-app-keba/hacbs-test-project-56fv@sha256:cf02c0e9f83495ad9787c47e401f54b57aec9a6a9a067fa70c3bbd0751bb0150
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
